# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descri\xe7\xe3o')),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('done', models.BooleanField(default=False, verbose_name='feita')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
